// <auto-generated />
using System;
using JogoTexto3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoTexto3.Migrations
{
    [DbContext(typeof(JogoDbContext))]
    [Migration("20240910222551_Create Database")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogoTexto3.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("JogoTexto3.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EastExitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NorthExitId")
                        .HasColumnType("int");

                    b.Property<int?>("SouthExitId")
                        .HasColumnType("int");

                    b.Property<int?>("WestExitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EastExitId");

                    b.HasIndex("NorthExitId");

                    b.HasIndex("SouthExitId");

                    b.HasIndex("WestExitId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("JogoTexto3.Models.Player", b =>
                {
                    b.HasOne("JogoTexto3.Models.Room", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("JogoTexto3.Models.Room", b =>
                {
                    b.HasOne("JogoTexto3.Models.Room", "EastExit")
                        .WithMany()
                        .HasForeignKey("EastExitId");

                    b.HasOne("JogoTexto3.Models.Room", "NorthExit")
                        .WithMany()
                        .HasForeignKey("NorthExitId");

                    b.HasOne("JogoTexto3.Models.Room", "SouthExit")
                        .WithMany()
                        .HasForeignKey("SouthExitId");

                    b.HasOne("JogoTexto3.Models.Room", "WestExit")
                        .WithMany()
                        .HasForeignKey("WestExitId");

                    b.Navigation("EastExit");

                    b.Navigation("NorthExit");

                    b.Navigation("SouthExit");

                    b.Navigation("WestExit");
                });
#pragma warning restore 612, 618
        }
    }
}
